const fruits = [
    {
        ref: "fruits_1",
        categoray: 0,
        name: "Citron",
        price: 0.99,
        unit: "pièce",
        image: "citron.png",
    },
    {
        ref: "fruits_2",
        categoray: 0,
        name: "Citron Vert",
        price: 1.99,
        unit: "pièce",
        image: "lime.jpg",
    },
    {
        ref: "fruits_3",
        categoray: 0,
        name: "Fraise",
        price: 2.99,
        unit: "kg",
        image: "fraise.png",
    },
    {
        ref: "fruits_4",
        categoray: 0,
        name: "Noix de Coco",
        price: 3.99,
        unit: "pièce",
        image: "coconut.jpg",
    },
    {
        ref: "fruits_5",
        categoray: 0,
        name: "Clémentine",
        price: 2.99,
        unit: "kg",
        image: "clementine.jpg",
    },
    {
        ref: "fruits_6",
        categoray: 0,
        name: "Figues",
        price: 5.99,
        unit: "kg",
        image: "figues.jpg",
    },
    {
        ref: "fruits_7",
        categoray: 0,
        name: "Raisins",
        price: 4.59,
        unit: "kg",
        image: "grapes.jpg",
    },
    {
        ref: "fruits_9",
        categoray: 0,
        name: "Poire",
        price: 3.49,
        unit: "kg",
        image: "poires.png",
    },
];

const legumes = [
    {
        ref: "legumes_1",
        categoray: 1,
        name: "Oignos",
        price: 0.99,
        unit: "kg",
        image: "oignons.jpg",
    },
    {
        ref: "legumes_2",
        categoray: 1,
        name: "Poivrons",
        price: 2.99,
        unit: "kg",
        image: "poovrons.jpg",
    },
    {
        ref: "legumes_3",
        categoray: 1,
        name: "Radis",
        price: 3.99,
        unit: "kg",
        image: "radis.jpg",
    },
    {
        ref: "legumes_4",
        categoray: 1,
        name: "Tomato",
        price: 2.99,
        unit: "kg",
        image: "tomato.jpg",
    },
    {
        ref: "legumes_5",
        categoray: 1,
        name: "Brocolis",
        price: 3.99,
        unit: "kg",
        image: "poovrons.jpg",
    },
    {
        ref: "legumes_6",
        categoray: 1,
        name: "Aubergine",
        price: 3.99,
        unit: "kg",
        image: "aubergine.jpg",
    },
    {
        ref: "legumes_7",
        categoray: 1,
        name: "Carotte",
        price: 3.99,
        unit: "kg",
        image: "carot.jpg",
    },
    {
        ref: "legumes_8",
        categoray: 1,
        name: "choux",
        price: 1.99,
        unit: "kg",
        image: "chou.jpg",
    },
];

const fresh = [
    {
        ref: "fresh_1",
        categoray: 2,
        name: "Milk",
        price: 2.99,
        unit: "pièce",
        image: "milk.jpg",
    },
    {
        ref: "fresh_2",
        categoray: 2,
        name: "Beure a tartine",
        price: 1.99,
        unit: "pièce",
        image: "beurre.jpg",
    },
    {
        ref: "fresh_3",
        categoray: 2,
        name: "Oeufs",
        price: 3.99,
        unit: "les douzes",
        image: "eggs.jpg",
    },
    {
        ref: "fresh_4",
        categoray: 2,
        name: "Yaourts Nature",
        price: 13.99,
        unit: "pièce",
        image: "yaourts_nature.jpg",
    },
    {
        ref: "fresh_5",
        categoray: 2,
        name: "Yaourts Fruits",
        price: 10.19,
        unit: "pièce",
        image: "yaourts_fruits.jpg",
    },
    
];
const epicerie = [
    {
        ref: "epicerie_1",
        categoray: 3,
        name: "Thon",
        price: 2.99,
        unit: "pièce",
        image: "thon.jpg",
    },
    {
        ref: "epicerie_2",
        categoray: 3,
        name: "Sardin",
        price: 1.99,
        unit: "pièce",
        image: "sardines.jpg",
    },
    {
        ref: "epicerie_3",
        categoray: 3,
        name: "Cookies",
        price: 3.99,
        unit: "pièce",
        image: "cookies.jpg",
    },
    {
        ref: "epicerie_4",
        categoray: 3,
        name: "Biscottes",
        price: 5.99,
        unit: "pièce",
        image: "biscottes.jpg",
    },
    {
        ref: "epicerie_5",
        categoray: 3,
        name: "Thé",
        price: 3.59,
        unit: "pièce",
        image: "the.jpg",
    },
    {
        ref: "epicerie_6",
        categoray: 3,
        name: "Soupes",
        price: 3.59,
        unit: "pièce",
        image: "soupe.jpg",
    },
    {
        ref: "epicerie_7",
        categoray: 3,
        name: "Pâtes",
        price: 3.59,
        unit: "pièce",
        image: "pates.jpg",
    },
];
const boissons = [
    {
        ref: "boissons_1",
        categoray: 4,
        name: "Vin Rouge",
        price: 12.59,
        unit: "pièce",
        image: "bordeaux.jpg",
    },
    {
        ref: "boissons_2",
        categoray: 4,
        name: "Vin Blanc",
        price: 11.99,
        unit: "pièce",
        image: "white.jpg",
    },
    {
        ref: "boissons_3",
        categoray: 4,
        name: "Riesling",
        price: 25.99,
        unit: "pièce",
        image: "riesling.jpg",
    },
    {
        ref: "boissons_4",
        categoray: 4,
        name: "Coca",
        price: 2.49,
        unit: "pièce",
        image: "coke.jpg",
    },
    {
        ref: "boissons_5",
        categoray: 4,
        name: "Sprite",
        price: 1.49,
        unit: "pièce",
        image: "sprite.jpg",
    },
    {
        ref: "boissons_6",
        categoray: 4,
        name: "Finley",
        price: 1.49,
        unit: "pièce",
        image: "finley.jpg",
    },
    {
        ref: "boissons_7",
        categoray: 4,
        name: "Nestea",
        price: 1.19,
        unit: "pièce",
        image: "nestea.jpg",
    },
    {
        ref: "boissons_8",
        categoray: 4,
        name: "Sprite",
        price: 1.49,
        unit: "pièce",
        image: "sprite.jpg",
    },
    {
        ref: "boissons_9",
        categoray: 4,
        name: "Sprite Zero",
        price: 1.49,
        unit: "pièce",
        image: "sprite_zero.jpg",
    },
];

export const list = [fruits, legumes, fresh, epicerie, boissons]